[package]
name = "blst-simple-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
description = "Simplified BLS signatures over blst"
repository = "https://github.com/efagerho/blst-simple-rs"

[features]
default = ["std", "signing"]
dangerous-proof-bypass = []
secret-key-export = ["signing"]
std = []
signing = []
portable = ["blst/portable"]

[dependencies]
blst = { version = "=0.3.17", default-features = false }
